name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: fetch tool
      run: ./fetch-tool.sh

    - name: build rootfs
      run: ./make-rootfs.sh

